name: tests

on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps: 
      - name: Print Hello Hexlet
        uses: hexlet-components/hello-from-hexlet-action@release

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - run: make setup
      - run: make test
      - run: make lint